import { ref, computed } from "vue";
import { defineStore } from "pinia";

export const useCounterStore = defineStore("counter", () => {
  const count = ref(0);
  const doubleCount = computed(() => count.value * 2);
  const mockData = [
    {
      title: "Mejor juego PS4/PS5",
      options: [
        "Call of Duty Warzone 2.0",
        "Cult of the Lamb",
        "Cuphead: The Delicious Last Course",
        "DNF Duel",
        "Dying Light 2: Stay Human",
        "Elden Ring",
        "Evil Dead: The Game",
        "God of War: Ragnarök",
        "Horizon Forbidden West",
        "Lego Star Wars: The Skywalker Saga",
        "MultiVersus",
        "Neon White",
        "Overwatch 2",
        "Rumbleverse",
        "Sifu",
        "Stray",
        "Teenage Mutant Ninja Turtles: Shredder's Revenge",
        "The King of Fighters XV",
        "Tunic",
        "Yu-Gi-Oh! Master Duel",
      ],
    },
    {
      title: "Mejor juego Xbox One/Series",
      options: [
        "As Dusk Falls",
        "Call of Duty Warzone 2.0",
        "Cult of the Lamb",
        "Cuphead: The Delicious Last Course",
        "Dying Light 2: Stay Human",
        "Elden Ring",
        "Evil Dead: The Game",
        "Grounded",
        "Immortality",
        "Lego Star Wars: The Skywalker Saga",
        "MultiVersus",
        "Overwatch 2",
        "Pentiment",
        "Rumbleverse",
        "Somerville",
        "Teenage Mutant Ninja Turtles: Shredder's Revenge",
        "The King of Fighters XV",
        "Tunic",
        "Vampire Survivors",
        "Yu-Gi-Oh! Master Duel",
      ],
    },
    {
      title: "Mejor juego Switch",
      options: [
        "Bayonetta 3",
        "Cult of the Lamb",
        "Cuphead: The Delicious Last Course",
        "Fire Emblem Warriors: Three Hopes",
        "Kirby and the Forgotten Land",
        "Lego Star Wars: The Skywalker Saga",
        "Live a Live",
        "Mario + Rabbids Sparks of Hope",
        "Neon White",
        "Nintendo Switch Sports",
        "Pokémon Legends: Arceus",
        "Pokémon Scarlet and Violet",
        "Radiant Silvergun",
        "Sifu",
        "Splatoon 3",
        "Teenage Mutant Ninja Turtles: Shredder's Revenge",
        "Tinykin",
        "Triangle Strategy",
        "Tunic",
        "Xenoblade Chronicles 3",
      ],
    },
    {
      title: "Mejor juego PC",
      options: [
        "Call of Duty Warzone 2.0",
        "Cult of the Lamb",
        "Cuphead: The Delicious Last Course",
        "DNF Duel",
        "Dying Light 2: Stay Human",
        "Elden Ring",
        "Evil Dead: The Game",
        "Immortality",
        "Lego Star Wars: The Skywalker Saga",
        "Marvel Snap",
        "MultiVersus",
        "Overwatch 2",
        "Pentiment",
        "Stray",
        "Teenage Mutant Ninja Turtles: Shredder's Revenge",
        "The King of Fighters XV",
        "Total War: Warhammer III",
        "Tunic",
        "Vampire Survivors",
        "Yu-Gi-Oh! Master Duel",
      ],
    },
    {
      title: "Mejor juego móvil",
      options: [
        "Apex Legends Mobile",
        "Diablo Immortal",
        "Disney Mirrorverse",
        "Isle of Arrows: Tower Defense",
        "Marvel Snap",
        "RPG Overrogue",
        "Soulvars",
        "Summoners War: Chronicles",
        "The Past Within",
        "Vampire Survivors",
      ],
    },
    {
      title: "Mejor juego multiplataforma",
      options: [
        "Call of Duty Warzone 2.0",
        "Cult of the Lamb",
        "Cuphead: The Delicious Last Course",
        "DNF Duel",
        "Dying Light 2: Stay Human",
        "Elden Ring",
        "Evil Dead: The Game",
        "Lego Star Wars: The Skywalker Saga",
        "Marvel Snap",
        "MultiVersus",
        "Neon White",
        "Overwatch 2",
        "Pentiment",
        "Sifu",
        "Stray",
        "Teenage Mutant Ninja Turtles: Shredder's Revenge",
        "The King of Fighters XV",
        "Tunic",
        "Vampire Survivors",
        "Yu-Gi-Oh! Master Duel",
      ],
    },
    {
      title: "Mejor empresa Third Party/desarrollador",
      options: [
        "Activision",
        "Andrew Shouldice",
        "Angel Matrix",
        "BlueTwelve Studio",
        "From Software",
        "Guerrilla Games",
        "Luca Galante",
        "Massive Monster",
        "Obsidian Entertainment",
        "Omega Force",
        "PlatinumGames",
        "Player First Games",
        "Traveller's Tales",
        "Tribute Games",
        "Sam Barlow",
        "Second Dinner",
        "Sloclap",
        "Square-Enix",
        "SNK",
        "Studio MDHR",
      ],
    },
    {
      title: "Mejor soundtrack",
      options: [
        "Bayonetta 3",
        "Cuphead: The Delicious Last Course",
        "Elden Ring",
        "Fire Emblem Warriors: Three Hopes",
        "God of War: Ragnarök",
        "Horizon Forbidden West",
        "Immortality",
        "Kirby and the Forgotten Land",
        "Live a Live",
        "Neon White",
        "Pentiment",
        "Pokémon Scarlet and Violet",
        "Sifu",
        "Splatoon 3",
        "Stray",
        "Teenage Mutant Ninja Turtles: Shredder's Revenge",
        "The King of Fighters XV",
        "Triangle Strategy",
        "Tunic",
        "Xenoblade Chronicles 3",
      ],
    },
    {
      title: "Mejor personaje",
      options: [
        "Aiden (Dying Light 2: Stay Human)",
        "Agent 3 (Splatoon 3)",
        "Aloy (Horizon Forbidden West)",
        "April O'Neil (Teenage Mutant Ninja Turtles: Shredder's Revenge)",
        "Ash Williams (Evil Dead: The Game)",
        "Atreus (God of War: Ragnarök)",
        "Gato (Stray)",
        "Isla (The King of Fighters XV)",
        "Kirby (Kirby and the Forgotten Land)",
        "Kiriko (Overwatch 2)",
        "Kratos (God of War: Ragnarök)",
        "Lamb (Cult of the Lamb)",
        "Ms. Chalice (Cuphead: The Delicious Last Course)",
        "Neon White (Neon White)",
        "Noah (Xenoblade Chronicles 3)",
        "Rabbids (Mario + Rabbids Sparks of Hope)",
        "Ruin Seeker (Tunic)",
        "Serenoa Wolffort (Triangle Strategy)",
        "Shaggy Rogers (MultiVersus)",
        "Shez (Fire Emblem Warriors: Three Hopes)",
      ],
    },
    {
      title: "Peor noticia del año en Gamercafe",
      options: [
        "A los 60 años falleció Kazuki Takahashi, creador y mangaka de Yu-Gi-Oh!",
        "A los 78 años murió Hidekazu Yukawa, recordado director ejecutivo de Sega",
        "Adiós FIFA: EA Sports cambiará el nombre de la franquicia a contar del 2023",
        "Arabia Saudita es “dueña” de SNK",
        "Cuenta regresiva de Code Mystics y Killer Instinct es modo en línea para… las cabinas de Arcade1Up",
        "Directo en la inflación: Steam ajusta los precios sugeridos para muchos paises",
        "El E3 2022 ha sido cancelado",
        "El fin de las tiendas virtuales de Nintendo 3DS y Wii U ocurrirá en Marzo de 2023",
        "El fin de una era: Toshimichi Mori, creador de BlazBlue, anuncia su retiro de Arc System Works",
        "El proyecto NFT de Ubisoft fracasa y culpa a los jugadores por no entender el concepto",
        "Espera, ¿qué?: Yuji Naka habría sido arrestado por “tráfico de información relacionado con Dragon Quest”",
        "Hasta siempre aniki: a los 74 años falleció Ichirou Mizuki",
        "Hellena Taylor, la voz de “Bayonetta,” llama a boicotear el juego",
        "Se ha filtrado un Alpha temprana de Grand Theft Auto VI",
        "¿Sorpresa?: Google anuncia que Stadia no va más y cerrará sus funciones el 18 de enero del 2023",
        "Konami celebrará el 35 aniversario de Castlevania… con NFTs",
        "PlayStation 5 subirá de precio en Latinoamérica y otros mercados",
        "PUCHA, EMPTY!: Ubisoft anuncia el fin de Hyper Scape",
        "Shinji Hashimoto anuncia su retiro de Square-Enix",
        "Tributo dentro de la Mega Drive Mini II habría confirmado el fallecimiento de Rieko Kodama",
      ],
      urls: [
        "https://www.gamercafe.cl/2022/07/07/a-los-60-anos-fallecio-kazuki-takahashi-creador-y-mangaka-de-yu-gi-oh/",
        "https://www.gamercafe.cl/2022/06/05/a-los-78-anos-murio-hidekazu-yukawa-recordado-director-ejecutivo-de-sega/",
        "https://www.gamercafe.cl/2022/05/10/adios-fifa-ea-sports-cambiara-el-nombre-de-la-franquicia-a-contar-del-2023/",
        "https://www.gamercafe.cl/2022/04/08/arabia-saudita-es-duena-de-snk/",
        "https://www.gamercafe.cl/2022/12/02/cuenta-regresiva-de-code-mystics-y-killer-instinct-es-modo-en-linea-para-las-cabinas-de-arcade1up/",
        "https://www.gamercafe.cl/2022/10/25/directo-en-la-inflacion-steam-ajusta-los-precios-sugeridos-para-muchos-paises/",
        "https://www.gamercafe.cl/2022/03/31/el-e3-2022-ha-sido-cancelado/",
        "https://www.gamercafe.cl/2022/02/16/el-fin-de-las-tiendas-virtuales-de-nintendo-3ds-y-wii-u-ocurrira-en-marzo-de-2023/",
        "https://www.gamercafe.cl/2022/09/25/el-fin-de-una-era-toshimichi-mori-creador-de-blazblue-anuncia-su-retiro-de-arc-system-works/",
        "https://www.gamercafe.cl/2022/01/31/el-proyecto-nft-de-ubisoft-fracasa-y-culpa-a-los-jugadores-por-no-entender-el-concepto/",
        "https://www.gamercafe.cl/2022/11/17/espera-que-yuji-naka-habria-sido-arrestado-por-trafico-de-informacion-relacionado-con-dragon-quest/",
        "https://www.gamercafe.cl/2022/12/12/hasta-siempre-aniki-a-los-74-anos-fallecio-ichirou-mizuki/",
        "https://www.gamercafe.cl/2022/10/16/hellena-taylor-la-voz-de-bayonetta-llama-a-boicotear-el-juego/",
        "https://www.gamercafe.cl/2022/09/18/se-ha-filtrado-un-alpha-temprana-de-grand-theft-auto-6/",
        "https://www.gamercafe.cl/2022/09/29/sorpresa-google-anuncia-que-stadia-no-va-mas-y-cerrara-sus-funciones-el-18-de-enero-del-2023/",
        "https://www.gamercafe.cl/2022/01/06/konami-celebrara-el-35-aniversario-de-castlevania-con-nfts/",
        "https://www.gamercafe.cl/2022/08/26/playstation-5-subira-de-precio-en-latinoamerica-y-otros-mercados/",
        "https://www.gamercafe.cl/2022/01/27/pucha-empty-ubisoft-anuncia-el-fin-de-hyper-scape/",
        "https://www.gamercafe.cl/2022/05/31/shinji-hashimoto-anuncia-su-retiro-de-square-enix/",
        "https://www.gamercafe.cl/2022/10/26/tributo-dentro-de-la-mega-drive-mini-ii-habria-confirmado-el-fallecimiento-de-rieko-kodama/",
      ],
    },
    {
      title: "Mejor noticia del año en Gamercafe",
      options: [
        "BigPEmu, el emulador de Atari Jaguar que asegura tener compatibilidad completa con todo el catálogo",
        "BloodbornePSX, el demake independiente para Windows con “gráficos tipo PS1”, ya está disponible",
        "Chaos Code NEXT revive y será mostrado en evento el 30 de abril",
        "“El EVO” regresa a Japón el 2023",
        "Guilty Gear Strive anuncia a Testament y segunda temporada con crossplay entre PS4/5 y Steam",
        "Justicia divina: aparece fantraducción al inglés de clásico de culto “Aconcagua” para PlayStation",
        "¿La “respuesta”?: Sony adquirió Bungie",
        "Metroid Dread se convierte en el juego más vendido de la franquicia",
        "¡Mi infancia!: Snow Bros. Nick & Tom Special está en desarrollo",
        "Planet Laika, el RPG de Quintet y Zeque para PS1, recibe fantraducción al inglés",
        "Project L, el juego de peleas de League of Legends, confirma oficialmente que será Free to Play",
        "SNK anuncia Beta abierta del rollback para la versión de Steam de Samurai Shodown",
        "Sorpresivo: Return to Monkey Island llega este año con el regreso de Ron Gilbert",
        "Splatoon 3 finalmente tiene fecha de lanzamiento",
        "STREET FIGHTER 6 y CAPCOM: Fighting Collection. Las sorpresas del countdown de CAPCOM.",
        "Subtle Style anuncia En-Eins Perfektwelt Anastasis para Arcades",
        "TRAILER: “The Super Mario Bros Movie”",
        "WELCOME TO NEW ERIDU – miHoYo revela ZENLESS ZONE ZERO",
        "Y finalmente llegó el día: Tokimeki Memorial recibe fantraducción al inglés (eso sí, el de SNES)",
        "Yasuyuki Oda de SNK afirma que “ambos lados están interesados en un nuevo SNK vs. Capcom”",
      ],
      urls: [
        "https://www.gamercafe.cl/2022/12/01/bigpemu-el-emulador-de-atari-jaguar-que-asegura-tener-compatibilidad-completa-con-todo-el-catalogo/",
        "https://www.gamercafe.cl/2022/01/31/bloodbornepsx-el-demake-independiente-para-windows-con-graficos-tipo-ps1-ya-esta-disponible/",
        "https://www.gamercafe.cl/2022/04/02/chaos-code-next-revive-y-sera-mostrado-en-evento-el-30-de-abril/",
        "https://www.gamercafe.cl/2022/08/11/el-evo-regresa-a-japon-el-2023/",
        "https://www.gamercafe.cl/2022/03/20/guilty-gear-strive-anuncia-a-testament-y-segunda-temporada-con-crossplay-entre-ps4-5-y-steam/",
        "https://www.gamercafe.cl/2022/07/11/justicia-divina-aparece-fantraduccion-al-ingles-de-clasico-de-culto-aconcagua-para-playstation/",
        "https://www.gamercafe.cl/2022/01/31/la-respuesta-sony-adquirio-bungie/",
        "https://www.gamercafe.cl/2022/05/10/metroid-dread-se-convierte-en-el-juego-mas-vendido-de-la-franquicia/",
        "https://www.gamercafe.cl/2022/02/16/mi-infancia-snow-bros-nick-tom-special-esta-en-desarrollo/",
        "https://www.gamercafe.cl/2022/02/14/planet-laika-el-rpg-de-quintet-y-zeque-para-ps1-recibe-fantraduccion-al-ingles/",
        "https://www.gamercafe.cl/2022/08/01/project-l-el-juego-de-peleas-de-league-of-legends-confirma-oficialmente-que-sera-free-to-play/",
        "https://www.gamercafe.cl/2022/11/23/snk-anuncia-beta-abierta-del-rollback-para-la-version-de-steam-de-samurai-shodown/",
        "https://www.gamercafe.cl/2022/04/04/return-to-monkey-island-llega-este-ano-con-el-regreso-de-ron-gilbert/",
        "https://www.gamercafe.cl/2022/04/26/splatoon-3-finalmente-tiene-fecha-de-lanzamiento/",
        "https://www.gamercafe.cl/2022/02/21/street-fighter-6-y-capcom-fighting-collection-las-sorpresas-del-countdown-de-capcom/",
        "https://www.gamercafe.cl/2022/02/21/subtle-style-anuncia-en-eins-perfektwelt-anastasis-para-arcades/",
        "https://www.gamercafe.cl/2022/10/07/trailer-the-super-mario-bros-movie/",
        "https://www.gamercafe.cl/2022/05/13/welcome-to-new-eridu-mihoyo-revela-zenless-zone-zero/",
        "https://www.gamercafe.cl/2022/03/07/y-finalmente-llego-el-dia-tokimeki-memorial-recibe-fantraduccion-al-ingles-eso-si-el-de-snes/",
        "https://www.gamercafe.cl/2022/08/30/yasuyuki-oda-de-snk-afirma-que-ambos-lados-estan-interesados-en-un-nuevo-snk-vs-capcom/",
      ],
    },
    {
      title: "Peor juego del año",
      options: [
        "Babylon's Fall",
        "CrossfireX",
        "Diablo Immortal",
        "Lego Brawls",
        "Postal 4: No Regrets",
        "The Last Oricru",
        "The Rumble Fish 2",
        "Write 'n' Fight",
        "XEL",
        "Zorro: The Chronicles",
      ],
    },
    {
      title: "Mejor juego del año",
      options: [
        "Bayonetta 3",
        "Cuphead: The Delicious Last Course",
        "Elden Ring",
        "Fire Emblem Warriors: Three Hopes",
        "God of War: Ragnarök",
        "Horizon Forbidden West",
        "Immortality",
        "Kirby and the Forgotten Land",
        "MultiVersus",
        "Pentiment",
        "Pokémon Scarlet and Violet",
        "Sifu",
        "Splatoon 3",
        "Stray",
        "Teenage Mutant Ninja Turtles: Shredder's Revenge",
        "The King of Fighters XV",
        "Tinykin",
        "Tunic",
        "Xenoblade Chronicles 3",
        "Vampire Survivors",
      ],
    },
  ];
  function increment() {
    count.value++;
  }

  return {
    count,
    doubleCount,
    increment,
  };
});
